logging.level: info
logging.to_files: false

#------------------------------ Log input --------------------------------
filebeat.inputs:
 - type: log
   enabled: true
   paths:
     - '/var/lib/docker/containers/logs/filebeat/*.log'
   json.keys_under_root: true

   processors:
     - decode_json_fields:
         fields: ['message']
         target: json

#========================== Elasticsearch output ===============================

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: changeme
  #index: "is-logs-filebeat-%{[observer.version]}-%{[processor.event]}-%{+yyyy.MM.dd}"

#setup.template:
  #name: 'is-logs-filebeat'
  #pattern: 'is-logs-filebeat-*'
  #enabled: false

#============================== Dashboards =====================================
# https://www.elastic.co/guide/en/beats/filebeat/current/configuration-dashboards.html

#setup.dashboards:
#  enabled: true
#setup.kibana:
#  host: "kibana:80"
#  username: elastic
#  password: changeme